### ISSUE TITLE
Could not delete Dark Souls: Prepare to Die Edition Steam Cloud files

### ISSUE THREAD

**Issue by chairborne** [GMMan/SteamCloudFileManagerLite#1]
![](https://cloud.githubusercontent.com/assets/12383418/13070389/f45c2700-d4ad-11e5-92fa-1cf698bcdf8a.png)
![](https://cloud.githubusercontent.com/assets/12383418/13070388/f45b7b84-d4ad-11e5-96d3-f1d0ce2da9ef.png)
It says there are some files (actually it's just my save game) but they could not be seen (even after refreshing). How is it possible and what should I do to delete them?

**Comment by GMMan** [comment]
The tool can only manage files uploaded programmatically through the Steamworks API. The game uses Steam's file system watching feature to sync saves, so to delete those, run the game, delete the files on disk, then exit the game, and Steam will sync up the changes. See [SteamDB](https://steamdb.info/app/211420/ufs/) for the path to save files.
