### ISSUE TITLE
Use as library

### ISSUE THREAD

**Issue by amadare42** [GMMan/SteamCloudFileManagerLite#11]
Firstly, thank you for your work and for sharing it with the community!

I'd want to have functionality similar to that you're already implemented. Is there any chance that you could extract core functionality as a library? I don't really want to copy all your relevant code and manually updating it on new versions.

I can create an update for your code and create PR if you're interested.

**Comment by GMMan** [comment]
It's probably best if you use Steamworks.NET directly, since this is mostly just a GUI around the Steam Cloud APIs. See https://github.com/rlabrecque/Steamworks.NET
