### ISSUE TITLE
Fails to connect

### ISSUE THREAD

**Issue by Bachsau** [GMMan/SteamCloudFileManagerLite#18]
I just took the time to install this on an old windows machine in the hope that I would finally be able to clean up the mess in my Steam Cloud. No such luck. What you see in the attachment is everything I got.

![crap](https://user-images.githubusercontent.com/2454271/179281943-44b38b67-694b-40d7-88de-ddc02887586a.png)

**Comment by GMMan** [comment]
Did you enter a valid app ID for a game that you own?

**Comment by Bachsau** [comment]
I used an app ID from a game that I once played using family sharing and that still has data stored in my cloud. If I use the ID of a game I actually own, I don't get the error message, but it shows nothing and zero bytes used even after refreshing.

Edit: It worked on a second attempt after restarting the app, but only with the game I own. Does this mean there is no way to access the data of games I'm not currently allowed to play?

**Comment by Bachsau** [comment]
Ok, I think I just now understood how this works. It mimics an installed and running game and relies completely on the Steam client to do the work. Sorry. I guess it is not possible for you to do more or access the Cloud in any other way, which sadly also means that everything this app does can also be achieved by just running the game and clearing out its save folder before killing the process.

**Comment by GMMan** [comment]
This only handles files stored using the remote storage interface. For auto-cloud files, those are handled by Steam itself and it doesn't expose them over the API.

**Comment by Bachsau** [comment]
Thanks for the clarification. I didn't know about the difference. At least for the games I own, I was finally able to clear out everything. While the savegames could only be deleted by removing them while the game was running, I had to use your app to get rid of the configuration files. I guess those are what the game manages through the remote storage API then.
