### ISSUE TITLE
Doesn't work without remote folder

### ISSUE THREAD

**Issue by JIMTIM12345** [GMMan/SteamCloudFileManagerLite#21]
Because not all game have a remote folder I don't think it  works withour it since when I tried to upload a file to kingdom two crowns it created a remote folder which doesn't exist by deafult

**Comment by JIMTIM12345** [comment]
What mean by doesn't work is that I can't see any files that should be there except the one I uploaded

**Comment by GMMan** [comment]
Some games only use auto-cloud and those files are not accessible via the Steam Cloud API.
