### ISSUE TITLE
how is this used or installed?

### ISSUE THREAD

**Issue by tsikows** [GMMan/SteamCloudFileManagerLite#4]
i dowloaded the file but theres no installation or anything just files

**Comment by GMMan** [comment]
No installation is necessary. Download from the builds page, run the EXE, and enter the app ID of the game you want to manage the Steam Cloud files of.

**Comment by tsikows** [comment]
Ahh after I re read the read me, this can not be used to download game saves?

**Comment by GMMan** [comment]
This will allow you to see all Steam Cloud files uploaded through the Steamworks API, but not any through auto-cloud.
