### ISSUE TITLE
Cannot initialize Steamworks API

### ISSUE THREAD

**Issue by sylveon** [GMMan/SteamCloudFileManagerLite#6]
![image](https://user-images.githubusercontent.com/6440374/30485596-e7ec1218-99fb-11e7-9e3a-3ba905cd1475.png)
I get this when trying to consult my DOOM steam cloud files.

**Comment by GMMan** [comment]
Is Steam running? Do you have CSteamworks.dll and steam_api.dll present in the same folder as the program?

**Comment by sylveon** [comment]
Yes, yes and yes

Tried as admin, but then the list is empty, even after multiple refresh (and yes there actually is data in my steam cloud)
![image](https://user-images.githubusercontent.com/6440374/30497532-278b2290-9a21-11e7-875e-433369a474c7.png)

**Comment by GMMan** [comment]
If you have to run the app as admin, it sounds like Steam is running as admin, which you shouldn't usually do. In any case, the app probably uses only auto-cloud, as seen [here](https://steamdb.info/app/379720/ufs/). Auto-cloud files are not exposed through the API, and you manage them by modifying the files while the game is running.

**Comment by sylveon** [comment]
Weird. I'm pretty sure I didn't start Steam as admin.

-- 
Envoyé de mon Gmail
