### ISSUE TITLE
Witcher 3

### ISSUE THREAD

**Issue by ayoits0913** [GMMan/SteamCloudFileManagerLite#8]
Works great with most games but when i try Witcher 3, its just blank. shows how much space i have used yet nothing is listed. Also, is this project dead? Seems still very relevant, wish someone would continue this....can't believe steam hasn't implemented something similar...

**Comment by GMMan** [comment]
The game uses [auto-cloud](https://steamdb.info/app/499450/ufs/), whose files do not show up in the API.

There's not really much other functionality in Steam Cloud that warrants additional changes.
